CREATE TABLE bank_account_history (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  FROM_BANK_ACCOUNT_ID bigint(20) NOT NULL,
  TO_BANK_ACCOUNT_ID bigint(20) NOT NULL,
  TRANSFERRED_AMOUNT decimal(19,2) DEFAULT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB